//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWReenviarSegundoIntento.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SWReenviarSegundoIntentoEntities : DbContext
    {
        public SWReenviarSegundoIntentoEntities()
            : base("name=SWReenviarSegundoIntentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_OBTENER_TODOS_LOS_CENTROS_Result> SP_OBTENER_TODOS_LOS_CENTROS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_TODOS_LOS_CENTROS_Result>("SP_OBTENER_TODOS_LOS_CENTROS");
        }
    
        public virtual ObjectResult<SP_SW_OBTENER_SEGUNDO_INTENTO_POR_CENTROID_Result> SP_SW_OBTENER_SEGUNDO_INTENTO_POR_CENTROID(Nullable<int> iN_ID_CENTRO)
        {
            var iN_ID_CENTROParameter = iN_ID_CENTRO.HasValue ?
                new ObjectParameter("IN_ID_CENTRO", iN_ID_CENTRO) :
                new ObjectParameter("IN_ID_CENTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SW_OBTENER_SEGUNDO_INTENTO_POR_CENTROID_Result>("SP_SW_OBTENER_SEGUNDO_INTENTO_POR_CENTROID", iN_ID_CENTROParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_SW_ACTUALIZAR_SEGUNDO_INTENTO(Nullable<int> iN_CATALOGO_ID, Nullable<int> iN_FICHA_STOCK_ID, Nullable<int> iN_CENTRO_ID, Nullable<int> iN_DESPACHO_ID)
        {
            var iN_CATALOGO_IDParameter = iN_CATALOGO_ID.HasValue ?
                new ObjectParameter("IN_CATALOGO_ID", iN_CATALOGO_ID) :
                new ObjectParameter("IN_CATALOGO_ID", typeof(int));
    
            var iN_FICHA_STOCK_IDParameter = iN_FICHA_STOCK_ID.HasValue ?
                new ObjectParameter("IN_FICHA_STOCK_ID", iN_FICHA_STOCK_ID) :
                new ObjectParameter("IN_FICHA_STOCK_ID", typeof(int));
    
            var iN_CENTRO_IDParameter = iN_CENTRO_ID.HasValue ?
                new ObjectParameter("IN_CENTRO_ID", iN_CENTRO_ID) :
                new ObjectParameter("IN_CENTRO_ID", typeof(int));
    
            var iN_DESPACHO_IDParameter = iN_DESPACHO_ID.HasValue ?
                new ObjectParameter("IN_DESPACHO_ID", iN_DESPACHO_ID) :
                new ObjectParameter("IN_DESPACHO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_SW_ACTUALIZAR_SEGUNDO_INTENTO", iN_CATALOGO_IDParameter, iN_FICHA_STOCK_IDParameter, iN_CENTRO_IDParameter, iN_DESPACHO_IDParameter);
        }
    
        public virtual ObjectResult<SP_OBTENER_INSUMOS_PACIENTE_POR_FICHA_Result> SP_OBTENER_INSUMOS_PACIENTE_POR_FICHA(Nullable<int> iN_ID_FICHA, Nullable<int> iN_ID_CENTRO)
        {
            var iN_ID_FICHAParameter = iN_ID_FICHA.HasValue ?
                new ObjectParameter("IN_ID_FICHA", iN_ID_FICHA) :
                new ObjectParameter("IN_ID_FICHA", typeof(int));
    
            var iN_ID_CENTROParameter = iN_ID_CENTRO.HasValue ?
                new ObjectParameter("IN_ID_CENTRO", iN_ID_CENTRO) :
                new ObjectParameter("IN_ID_CENTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_INSUMOS_PACIENTE_POR_FICHA_Result>("SP_OBTENER_INSUMOS_PACIENTE_POR_FICHA", iN_ID_FICHAParameter, iN_ID_CENTROParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GUARDAR_STOCK_PACIENTE(Nullable<int> iN_ID_FICHA_STOCK)
        {
            var iN_ID_FICHA_STOCKParameter = iN_ID_FICHA_STOCK.HasValue ?
                new ObjectParameter("IN_ID_FICHA_STOCK", iN_ID_FICHA_STOCK) :
                new ObjectParameter("IN_ID_FICHA_STOCK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GUARDAR_STOCK_PACIENTE", iN_ID_FICHA_STOCKParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_INSERTAR_ORDEN_COMPRA_AUTO(Nullable<int> iN_ID_LICITACION, string iN_CODIGO_ORDEN_COMPRA, Nullable<int> iN_ID_PROVEEDOR, Nullable<int> iN_ID_MONEDA, Nullable<int> iN_ID_PAIS, Nullable<int> iN_ID_TIPO_OC, string iN_DESCRIPCION, string iN_NOMBRE, Nullable<int> iN_ID_CENTRO)
        {
            var iN_ID_LICITACIONParameter = iN_ID_LICITACION.HasValue ?
                new ObjectParameter("IN_ID_LICITACION", iN_ID_LICITACION) :
                new ObjectParameter("IN_ID_LICITACION", typeof(int));
    
            var iN_CODIGO_ORDEN_COMPRAParameter = iN_CODIGO_ORDEN_COMPRA != null ?
                new ObjectParameter("IN_CODIGO_ORDEN_COMPRA", iN_CODIGO_ORDEN_COMPRA) :
                new ObjectParameter("IN_CODIGO_ORDEN_COMPRA", typeof(string));
    
            var iN_ID_PROVEEDORParameter = iN_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("IN_ID_PROVEEDOR", iN_ID_PROVEEDOR) :
                new ObjectParameter("IN_ID_PROVEEDOR", typeof(int));
    
            var iN_ID_MONEDAParameter = iN_ID_MONEDA.HasValue ?
                new ObjectParameter("IN_ID_MONEDA", iN_ID_MONEDA) :
                new ObjectParameter("IN_ID_MONEDA", typeof(int));
    
            var iN_ID_PAISParameter = iN_ID_PAIS.HasValue ?
                new ObjectParameter("IN_ID_PAIS", iN_ID_PAIS) :
                new ObjectParameter("IN_ID_PAIS", typeof(int));
    
            var iN_ID_TIPO_OCParameter = iN_ID_TIPO_OC.HasValue ?
                new ObjectParameter("IN_ID_TIPO_OC", iN_ID_TIPO_OC) :
                new ObjectParameter("IN_ID_TIPO_OC", typeof(int));
    
            var iN_DESCRIPCIONParameter = iN_DESCRIPCION != null ?
                new ObjectParameter("IN_DESCRIPCION", iN_DESCRIPCION) :
                new ObjectParameter("IN_DESCRIPCION", typeof(string));
    
            var iN_NOMBREParameter = iN_NOMBRE != null ?
                new ObjectParameter("IN_NOMBRE", iN_NOMBRE) :
                new ObjectParameter("IN_NOMBRE", typeof(string));
    
            var iN_ID_CENTROParameter = iN_ID_CENTRO.HasValue ?
                new ObjectParameter("IN_ID_CENTRO", iN_ID_CENTRO) :
                new ObjectParameter("IN_ID_CENTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_INSERTAR_ORDEN_COMPRA_AUTO", iN_ID_LICITACIONParameter, iN_CODIGO_ORDEN_COMPRAParameter, iN_ID_PROVEEDORParameter, iN_ID_MONEDAParameter, iN_ID_PAISParameter, iN_ID_TIPO_OCParameter, iN_DESCRIPCIONParameter, iN_NOMBREParameter, iN_ID_CENTROParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GENERACION_DE_DESPACHOS_REPOSICION_AUTO(Nullable<int> iN_CENTROID, Nullable<int> iN_USUARIOID)
        {
            var iN_CENTROIDParameter = iN_CENTROID.HasValue ?
                new ObjectParameter("IN_CENTROID", iN_CENTROID) :
                new ObjectParameter("IN_CENTROID", typeof(int));
    
            var iN_USUARIOIDParameter = iN_USUARIOID.HasValue ?
                new ObjectParameter("IN_USUARIOID", iN_USUARIOID) :
                new ObjectParameter("IN_USUARIOID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GENERACION_DE_DESPACHOS_REPOSICION_AUTO", iN_CENTROIDParameter, iN_USUARIOIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_INSERTAR_NUEVA_REPOSICION_AUTO(Nullable<int> iN_NID_CATALOGO, Nullable<int> iN_NID_FICHA_STOCK, Nullable<int> iN_NID_USUARIO, string iN_SCOMENTARIO, Nullable<int> iN_NID_CENTRO, Nullable<int> iN_NID_ORDEN_COMPRA, Nullable<int> iN_NID_CONSIGNACION, Nullable<int> iN_NID_DESPACHO)
        {
            var iN_NID_CATALOGOParameter = iN_NID_CATALOGO.HasValue ?
                new ObjectParameter("IN_NID_CATALOGO", iN_NID_CATALOGO) :
                new ObjectParameter("IN_NID_CATALOGO", typeof(int));
    
            var iN_NID_FICHA_STOCKParameter = iN_NID_FICHA_STOCK.HasValue ?
                new ObjectParameter("IN_NID_FICHA_STOCK", iN_NID_FICHA_STOCK) :
                new ObjectParameter("IN_NID_FICHA_STOCK", typeof(int));
    
            var iN_NID_USUARIOParameter = iN_NID_USUARIO.HasValue ?
                new ObjectParameter("IN_NID_USUARIO", iN_NID_USUARIO) :
                new ObjectParameter("IN_NID_USUARIO", typeof(int));
    
            var iN_SCOMENTARIOParameter = iN_SCOMENTARIO != null ?
                new ObjectParameter("IN_SCOMENTARIO", iN_SCOMENTARIO) :
                new ObjectParameter("IN_SCOMENTARIO", typeof(string));
    
            var iN_NID_CENTROParameter = iN_NID_CENTRO.HasValue ?
                new ObjectParameter("IN_NID_CENTRO", iN_NID_CENTRO) :
                new ObjectParameter("IN_NID_CENTRO", typeof(int));
    
            var iN_NID_ORDEN_COMPRAParameter = iN_NID_ORDEN_COMPRA.HasValue ?
                new ObjectParameter("IN_NID_ORDEN_COMPRA", iN_NID_ORDEN_COMPRA) :
                new ObjectParameter("IN_NID_ORDEN_COMPRA", typeof(int));
    
            var iN_NID_CONSIGNACIONParameter = iN_NID_CONSIGNACION.HasValue ?
                new ObjectParameter("IN_NID_CONSIGNACION", iN_NID_CONSIGNACION) :
                new ObjectParameter("IN_NID_CONSIGNACION", typeof(int));
    
            var iN_NID_DESPACHOParameter = iN_NID_DESPACHO.HasValue ?
                new ObjectParameter("IN_NID_DESPACHO", iN_NID_DESPACHO) :
                new ObjectParameter("IN_NID_DESPACHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_INSERTAR_NUEVA_REPOSICION_AUTO", iN_NID_CATALOGOParameter, iN_NID_FICHA_STOCKParameter, iN_NID_USUARIOParameter, iN_SCOMENTARIOParameter, iN_NID_CENTROParameter, iN_NID_ORDEN_COMPRAParameter, iN_NID_CONSIGNACIONParameter, iN_NID_DESPACHOParameter);
        }
    
        public virtual ObjectResult<SP_OBTENER_INFO_CORREO_Result> SP_OBTENER_INFO_CORREO(Nullable<int> iN_ID_FICHA_STOCK)
        {
            var iN_ID_FICHA_STOCKParameter = iN_ID_FICHA_STOCK.HasValue ?
                new ObjectParameter("IN_ID_FICHA_STOCK", iN_ID_FICHA_STOCK) :
                new ObjectParameter("IN_ID_FICHA_STOCK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_INFO_CORREO_Result>("SP_OBTENER_INFO_CORREO", iN_ID_FICHA_STOCKParameter);
        }
    
        public virtual ObjectResult<SP_OBTENER_DIRECCIONES_EMAIL_POR_PROVEEDOR_Result> SP_OBTENER_DIRECCIONES_EMAIL_POR_PROVEEDOR(Nullable<int> iN_ID_CORREO_AUTOMATICO, Nullable<int> iN_ID_PROVEEDOR, Nullable<int> iN_ID_CENTRO, Nullable<int> iN_ID_TERRITORIO)
        {
            var iN_ID_CORREO_AUTOMATICOParameter = iN_ID_CORREO_AUTOMATICO.HasValue ?
                new ObjectParameter("IN_ID_CORREO_AUTOMATICO", iN_ID_CORREO_AUTOMATICO) :
                new ObjectParameter("IN_ID_CORREO_AUTOMATICO", typeof(int));
    
            var iN_ID_PROVEEDORParameter = iN_ID_PROVEEDOR.HasValue ?
                new ObjectParameter("IN_ID_PROVEEDOR", iN_ID_PROVEEDOR) :
                new ObjectParameter("IN_ID_PROVEEDOR", typeof(int));
    
            var iN_ID_CENTROParameter = iN_ID_CENTRO.HasValue ?
                new ObjectParameter("IN_ID_CENTRO", iN_ID_CENTRO) :
                new ObjectParameter("IN_ID_CENTRO", typeof(int));
    
            var iN_ID_TERRITORIOParameter = iN_ID_TERRITORIO.HasValue ?
                new ObjectParameter("IN_ID_TERRITORIO", iN_ID_TERRITORIO) :
                new ObjectParameter("IN_ID_TERRITORIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_DIRECCIONES_EMAIL_POR_PROVEEDOR_Result>("SP_OBTENER_DIRECCIONES_EMAIL_POR_PROVEEDOR", iN_ID_CORREO_AUTOMATICOParameter, iN_ID_PROVEEDORParameter, iN_ID_CENTROParameter, iN_ID_TERRITORIOParameter);
        }
    
        public virtual ObjectResult<SP_SW_OBTENER_INSUMOS_NO_CONFIRMADOS_POR_CENTROID_Result> SP_SW_OBTENER_INSUMOS_NO_CONFIRMADOS_POR_CENTROID(Nullable<int> iN_ID_CENTRO)
        {
            var iN_ID_CENTROParameter = iN_ID_CENTRO.HasValue ?
                new ObjectParameter("IN_ID_CENTRO", iN_ID_CENTRO) :
                new ObjectParameter("IN_ID_CENTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SW_OBTENER_INSUMOS_NO_CONFIRMADOS_POR_CENTROID_Result>("SP_SW_OBTENER_INSUMOS_NO_CONFIRMADOS_POR_CENTROID", iN_ID_CENTROParameter);
        }
    }
}
